### ISSUE TITLE
Warning on blocking calls in Zaptec API

### ISSUE THREAD

**Issue by sveinse** [custom-components/zaptec#116]
With reference to #105 , HA is giving warnings about blocking calls from running the Zaptec integration.

The full error:

```
2024-09-07 18:11:24.422 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to
load_verify_locations with args (<ssl.SSLContext object at 0x7f3bdcc79750>,
'/home/vscode/.local/ha-venv/lib/python3.12/site-packages/certifi/cacert.pem') inside the event loop
by custom integration 'zaptec' at custom_components/zaptec/api.py, line 321: async with receiver:
(offender: /home/vscode/.local/ha-venv/lib/python3.12/site-packages/azure/servicebus/_pyamqp/aio/_transport_async.py,
 line 198: context.load_verify_locations(ca_certs)), please report it to the author of the 'zaptec' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "/home/vscode/.local/ha-venv/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/workspaces/ha-core/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/workspaces/ha-core/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1978, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/workspaces/ha-core/config/custom_components/zaptec/api.py", line 321, in _stream
    async with receiver:
```

**Comment by sveinse** [comment]
The cause for the warning is from `azure-servicebus` which sets up an `ssl.SSLContext()` and calls `context.load_verify_locations()` which is a blocking operations when it fetches the certificates from disk.

**Comment by sveinse** [comment]
The upstream issue is tracked here: https://github.com/Azure/azure-sdk-for-python/issues/37246

**Comment by sveinse** [comment]
When this fix in `azure-servicebus` is fixed upstream, please note that it is being used and pinned by a component in the HA core. This must probably be taken into consideration by submitting a PR to (HA) core when fix is available. https://github.com/home-assistant/core/blob/dev/homeassistant/components/azure_service_bus/manifest.json
